zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"
boilerbay:
  build: .
  links:
    - zookeeper:zk
    - kafka:kfk
  ports:
    - "4444:4444"
kafka:
  image: wurstmeister/kafka
  ports:
    - "9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
